theme = "github.com/bep/docuapi"
themesDir = "themes"
languageCode = "en-us"
baseurl = "https://cobalt-api.netlify.com/"
title = "Cobalt API Documentation"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
        unsafe = true

[module]
[module.hugoVersion]
[[module.imports]]
path="github.com/bep/docuapi"

[params]
search = true

# Configure the language example tabs.
[[params.language_tabs]]
key = "shell"
name = "Shell"

# These are commented out for now.
#[[params.language_tabs]]
#key = "ruby"
#name = "Ruby"
#[[params.language_tabs]]
#key = "python"
#name = "Python"
#[[params.language_tabs]]
#key = "javascript"
#name = "Javascript"

#Languages
[languages]

[languages.en]
languageName = "English"
weight = 2
title = "Cobalt API Documentation"

# Left sidebar footer items. Use HTMl or Markdown.
toc_footers = [
"<a href='https://app.cobalt.io/settings/api-token' rel='nofollow' target='_new'>Create your personal API token</a>",
"<a href='https://app.swaggerhub.com/apis/CobaltLab/cobalt-api/' target='_new'>Explore our API in Swagger</a>",
"Visit our [Support Center](https://cobaltio.zendesk.com/hc/en-us)"
]
[languages.en.blackfriday]
angledQuotes = false
hrefTargetBlank = true
