version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "github-actions"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "gomod"
    groups:
      minor-updates: # Update all minor and security versions
        applies-to: version-updates
        patterns:
        - "*"
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "docker"
