version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 2
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Berlin"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:30"
      timezone: "Europe/Berlin"
