# rule defaults can be found on:
#   - https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.jsonc
#   - https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# MD013/line-length - Line length
MD013:
  line_length: 120
  code_blocks: true
  tables: false

# MD033/no-inline-html - Inline HTML
MD033: false

# MD025/single-title/single-h1 - Multiple top-level headings in the same document
MD025: false
