[build]
command = "hugo --gc --minify --config='versions/v1/config.yaml' && hugo --gc --minify --config='versions/v2/config.yaml'"

[context.production.environment]
HUGO_VERSION = "0.102.3"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture --config='versions/v1/config.yaml' && hugo --gc --minify --buildFuture --config='versions/v2/config.yaml'"

[context.deploy-preview.environment]
HUGO_VERSION = "0.102.3"

[context.branch-deploy]
command = "hugo --gc --minify --buildFuture --config='versions/v1/config.yaml' && hugo --gc --minify --buildFuture --config='versions/v2/config.yaml'"

[context.branch-deploy.environment]
HUGO_VERSION = "0.102.3"

[[redirects]]
  from = "/"
  to = "/v2"

  # The default HTTP status code is 301, but you can
  # define a different one.
  status = 302

  # By default, redirects won’t be applied if there’s a file
  # with the same path as the one defined in the `from` property.
  # Setting `force` to `true` will make the redirect rule
  # take precedence over any existing files.
  force = true
