# core settings
baseurl: https://cobalt-public-api.netlify.com/v2
languageCode: en-us
title: Cobalt API Documentation
contentDir: versions/v2/content
publishDir: public/v2

# theme settings
theme: github.com/bep/docuapi/v2
themesDir: themes
module:
  imports:
    - path: github.com/bep/docuapi/v2

# syntax highlighting
pygmentsCodefences: true
pygmentsCodeFencesGuesSsyntax: false
pygmentsOptions: ""
pygmentsStyle: monokai
pygmentsUseClasses: false
defaultContentLanguage: en
markup:
  goldmark:
    parser:
      autoHeadingIDType: github-ascii
    renderer:
      unsafe: true

# site params
params:
  search: true
  language_tabs:
    - key: shell
      name: Shell
disableKinds:
  - taxonomyTerm

# sidebar settings
languages:
  en:
    languageName: English
    weight: 1
    title: Cobalt API Documentation
    toc_footers:
      - <a href='/v1' rel='nofollow'
        target='_new'>View API v1 Documentation</a>
      - <a href='https://app.cobalt.io/settings/api-token' rel='nofollow'
        target='_new'>Create Your Personal API Token</a>
      - <a href='https://developer.cobalt.io/'
        target='_new'>Read Cobalt Documentation</a>
