name: build

on: push

permissions:
  contents: read

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Check markdown files to detect broken links
        uses: gaurav-nelson/github-action-markdown-link-check@3c3b66f1f7d0900e37b71eca45b63ea9eedfce31 # 1.0.17
        with:
          folder-path: 'versions/v1/content, versions/v2/content'
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
      - name: Lint markdown files
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: 'versions/**/content/*.md'
          config: '.markdownlint.yaml'
