name: build

on: push

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - name: Check markdown files to detect broken links
        uses: gaurav-nelson/github-action-markdown-link-check@9710f0fec812ce0a3b98bef4c9d842fc1f39d976 # 1.0.14
        with:
          folder-path: 'versions/v1/content, versions/v2/content'
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
      - name: Lint markdown files
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: 'versions/**/content/*.md'
          config: '.markdownlint.yaml'
