name: build

on: push

jobs:
  markdown:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Check markdown files to detect broken links
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # 1.0.14
        with:
          folder-path: 'versions/v1/content, versions/v2/content'
          use-quiet-mode: 'no'
          use-verbose-mode: 'yes'
      - name: Lint markdown files
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          args: 'versions/**/content/*.md'
          config: '.markdownlint.yaml'
