name: Vale Editorial Review

on: [pull_request]

# Official GitHub Action from Vale https://github.com/errata-ai/vale-action
jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

      - name: Vale Grammar Linter
        uses: errata-ai/vale-action@c4213d4de3d5f718b8497bd86161531c78992084 # v2.0.1
        with:
          fail_on_error: true
          files: versions/
        env:
          # Required, set by GitHub actions automatically:
          # https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
