name: Editorial Review

on: push

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Vale Grammar Linter
        uses: errata-ai/vale-action@reviewdog
        with:
          args: 'versions/'